"""Auto-generate the server's reference documentation.

Usage:
    python scripts/generate_docs.py [--out docs/auto]   # write the pages
    python scripts/generate_docs.py --check             # validate + idempotency (CI)

The generated pages are pure output of their sources of truth and are never
committed (they are produced by GitHub Actions into the gitignored
``docs/auto/`` folder and published through mkdocs):

    docs/auto/commands.md   <- CommandLister over server/commands/* docstrings
    docs/auto/prefs.md      <- AREA_PREFS_META + live Area boolean defaults
    docs/auto/hub_prefs.md  <- HUB_PREFS_META + live AreaManager boolean defaults

Never edit a generated page. Hand-written companion docs (docs/index.md,
docs/in_character.md, docs/demo_scripting.md) are committed and untouched.
"""

import argparse
import os
import re
import sys
import tempfile
import types
from pathlib import Path

import oyaml as yaml

# Allow running as `python scripts/generate_docs.py` from any cwd.
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from server.schema.area_fields import (  # noqa: E402
    AREA_PREFS_META,
    HUB_PREFS_META,
)
from server.schema.commands_meta import CommandLister  # noqa: E402

_BANNER = (
    "<!-- AUTO-GENERATED by scripts/generate_docs.py -- do not edit. -->\n"
    "<!-- Sources: server/commands docstrings + server/schema/area_fields.py. -->\n"
)

_TIER_LABELS = {
    "public": "",
    "area_owners": "*CM*",
    "hub_owners": "*GM*",
    "any_owner": "*CM/GM*",
    "mod_only": "*Mod*",
}

_COMMAND_INTRO = """\
> This page is the auto-generated reference for every OOC `/` command shipped by
> the server. It is built from the commands' own docstrings — if you notice stale
> or missing info here, fix the docstring in `server/commands/`.

`<>` mean "required arguments", `[]` mean "optional arguments". Actual commands
do not need these brackets.

Permission tiers, shown in parentheses next to each command:

- no tag — usable by everyone
- *(CM)* — Case Makers and above (CMs, GMs and mods)
- *(GM)* — Game Masters and above
- *(Mod)* — moderators only

Servers may add or remove aliases in their `config/command_aliases.yaml` — each
entry below lists the aliases from the sample configuration.

The in-character chat prefixes (`/a`, `/w`, the testimony markers) are **not**
OOC commands; they are documented in [In-Character Commands](../in_character.md).
"""

_PREFS_INTRO = """\
> This page documents every boolean area preference settable with `/area_pref`.
> Each entry shows the attribute name, the server default, what it does, and who
> is allowed to toggle it.

Defaults shown are the server's startup defaults. Prefs marked *System state*
are driven by other commands (e.g. `/lights`, `/area_lock`) — do not flip them
directly.
"""

_HUB_PREFS_INTRO = """\
> This page documents every boolean hub preference. Hub preferences are managed
> by Game Masters through the toggle commands noted next to each entry (or
> directly in `config/areas.yaml`).
"""


# ---------------------------------------------------------------------------
# Catalog / aliases
# ---------------------------------------------------------------------------


def collect_catalog():
    """Command catalog from CommandLister, grouped by submodule (sorted)."""
    return CommandLister.to_groups()


def load_aliases():
    """Reverse-map `config_sample/command_aliases.yaml` -> {command: [alias...]}."""
    path = ROOT / "config_sample" / "command_aliases.yaml"
    with open(path, "r", encoding="utf-8") as fh:
        raw = yaml.safe_load(fh) or {}
    by_command = {}
    for alias, target in raw.items():
        by_command.setdefault(str(target), [])
        by_command[str(target)].append(str(alias))
    for aliases in by_command.values():
        aliases.sort()
    return by_command


# ---------------------------------------------------------------------------
# Pref introspection (defaults read live off real instances)
# ---------------------------------------------------------------------------


def _live_area():
    from server.area import Area

    return Area(types.SimpleNamespace(), "Test")


def _live_hub():
    from server.area_manager import AreaManager

    hub_stub = types.SimpleNamespace(server=types.SimpleNamespace(char_list=[]))
    return AreaManager(hub_stub, "Test")


def _bool_scoreboard(obj):
    """Sorted list of (attr, default) for a constructed instance's bool attrs."""
    out = []
    for key, value in vars(obj).items():
        if not key.startswith("_") and type(value) is bool:
            out.append((key, value))
    out.sort(key=lambda pair: pair[0])
    return out


def collect_area_prefs():
    """[(name, default, meta)] for every boolean Area attribute."""
    defaults = dict(_bool_scoreboard(_live_area()))
    return [
        (name, defaults[name], AREA_PREFS_META[name])
        for name in sorted(defaults)
    ]


def collect_hub_prefs():
    """[(name, default, meta)] for every boolean AreaManager attribute."""
    defaults = dict(_bool_scoreboard(_live_hub()))
    return [
        (name, defaults[name], HUB_PREFS_META[name])
        for name in sorted(defaults)
    ]


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate(catalog, area_prefs, hub_prefs):
    """Return a list of human-readable problems (empty means OK)."""
    errors = []
    for group in catalog:
        for cmd in group["commands"]:
            if not cmd["summary"]:
                errors.append(
                    f"[commands/{group['module']}] {cmd['name']} has no docstring."
                )
            if not cmd["usage"]:
                errors.append(
                    f"[commands/{group['module']}] {cmd['name']} has no 'Usage:' line."
                )
    area_names = {name for name, _, _ in area_prefs}
    if set(AREA_PREFS_META) != area_names:
        missing = sorted(set(AREA_PREFS_META) - area_names)
        unknown = sorted(area_names - set(AREA_PREFS_META))
        if missing:
            errors.append(f"[area prefs] metadata for missing attrs: {', '.join(missing)}")
        if unknown:
            errors.append(f"[area prefs] undocumented attrs: {', '.join(unknown)}")
    for name, meta in AREA_PREFS_META.items():
        if not meta.get("description"):
            errors.append(f"[area prefs] {name} lacks a description.")
    hub_names = {name for name, _, _ in hub_prefs}
    if set(HUB_PREFS_META) != hub_names:
        missing = sorted(set(HUB_PREFS_META) - hub_names)
        unknown = sorted(hub_names - set(HUB_PREFS_META))
        if missing:
            errors.append(f"[hub prefs] metadata for missing attrs: {', '.join(missing)}")
        if unknown:
            errors.append(f"[hub prefs] undocumented attrs: {', '.join(unknown)}")
    for name, meta in HUB_PREFS_META.items():
        if not meta.get("description"):
            errors.append(f"[hub prefs] {name} lacks a description.")
    return errors


# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------


def _usage_line(command):
    usage = command["usage"].strip()
    if not usage:
        args = _fallback_usage_args(command)
        usage = f"Usage: /{command['name']}" + (f" {args}" if args else "")
    return re.sub(r"\s+", " ", usage).strip()


def _fallback_usage_args(command):
    tokens = []
    for arg in command["args"]:
        name = arg["name"]
        if arg["rest"] or arg["variadic"]:
            tokens.append(f"[{name}...]")
        elif arg["required"]:
            tokens.append(f"<{name}>")
        else:
            tokens.append(f"[{name}]")
    return " ".join(tokens)


def _doc_body(doc, command):
    """Docstring lines minus the Usage: line(s), indented as markdown bullets."""
    lines = []
    for raw in doc.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.lower().startswith("usage:"):
            continue
        lines.append("    " + line)
    for arg in command["args"]:
        if not arg["help"]:
            continue
        role = "required" if arg["required"] else "optional"
        extra = ""
        if not arg["required"] and arg["default"] not in (None, ""):
            extra = f", default {arg['default']}"
        lines.append(f"    - Argument `{arg['name']}` ({role}{extra}): {arg['help']}")
    return lines


def _tier(command):
    label = _TIER_LABELS.get(command["permission"], "")
    return f" ({label})" if label else ""


def _tier_explain():
    return (
        "Tier legend: *(CM)* = Case Makers and above, *(GM)* = Game Masters and "
        "above, *(Mod)* = moderators only; no tag means everyone."
    )


def _command_block(command, aliases_by_command):
    usage = _usage_line(command)
    out = [f"* **{command['name']}** `{usage}`{_tier(command)}"]
    out.extend(_doc_body(command["docs"], command))
    aliases = aliases_by_command.get(command["name"])
    if aliases:
        out.append("    - Aliases: " + ", ".join(f"`{a}`" for a in aliases))
    return out


def _pref_block(name, default, meta):
    out = [f"* **{name}** *(default: {default})*"]
    out.append(f"    - {meta['description']}")
    note = meta.get("note")
    if note:
        out.append(f"    - *{note}*")
    return out


def _module_title(module):
    return module.replace("_", " ").title()


# ---------------------------------------------------------------------------
# Page renderers
# ---------------------------------------------------------------------------


def render_commands(alias_map=None):
    catalog = collect_catalog()
    aliases = alias_map if alias_map is not None else load_aliases()
    out = [_BANNER, "# Commands", "", _COMMAND_INTRO, ""]
    for group in catalog:
        out.append(f"## {_module_title(group['module'])}")
        out.append("")
        for command in group["commands"]:
            out.extend(_command_block(command, aliases))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_prefs():
    area_prefs = collect_area_prefs()
    out = [_BANNER, "# Area Prefs", "", _PREFS_INTRO, ""]
    groups = [
        ("## Case Makers and above", lambda n, d, m: m.get("cm_allowed") and not m.get("internal")),
        ("## Game Masters and above", lambda n, d, m: not m.get("cm_allowed") and not m.get("internal")),
        ("## System state (do not change directly)", lambda n, d, m: bool(m.get("internal"))),
    ]
    for heading, keep in groups:
        entries = [(n, d, m) for n, d, m in area_prefs if keep(n, d, m)]
        out.append(heading)
        out.append("")
        for name, default, meta in entries:
            out.extend(_pref_block(name, default, meta))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_hub_prefs():
    hub_prefs = collect_hub_prefs()
    out = [_BANNER, "# Hub Prefs", "", _HUB_PREFS_INTRO, ""]
    out.append("## Game Masters and above")
    out.append("")
    for name, default, meta in hub_prefs:
        out.extend(_pref_block(name, default, meta))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


PAGES = {
    "commands.md": render_commands,
    "prefs.md": render_prefs,
    "hub_prefs.md": render_hub_prefs,
}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def render_all(out_dir):
    """Write every generated page into `out_dir`; returns {filename: content}."""
    rendered = {name: fn() for name, fn in PAGES.items()}
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in rendered.items():
        (out_dir / name).write_text(content, encoding="utf-8")
    return rendered


def check(out_dir):
    """CI/validity gate: validate sources and assert deterministic output.

    Returns (ok, message).
    """
    errors = validate(collect_catalog(), collect_area_prefs(), collect_hub_prefs())
    if errors:
        return False, "Validation failed:\n" + "\n".join(f"  - {e}" for e in errors)

    with tempfile.TemporaryDirectory() as tmp:
        first = render_all(tmp)
        rendered_twice = []
        for name in PAGES:
            rendered_twice.append((name, first[name]))
            with open(Path(tmp) / name, "r", encoding="utf-8") as fh:
                second = fh.read()
            if first[name] != second:
                return False, f"Non-deterministic output for {name}."

    out_dir = Path(out_dir)
    if out_dir.is_dir():
        diffs = []
        for name, content in first.items():
            path = out_dir / name
            if path.exists() and path.read_text(encoding="utf-8") != content:
                diffs.append(name)
        if diffs:
            return False, "Generated pages out of date: " + ", ".join(sorted(diffs))
    return True, "OK: sources validated, output deterministic."


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate KFO server reference docs.")
    parser.add_argument("--out", default=str(ROOT / "docs" / "auto"), help="output dir")
    parser.add_argument("--check", action="store_true", help="validate + idempotency check")
    args = parser.parse_args(argv)

    if args.check:
        ok, message = check(args.out)
        print(message)
        return 0 if ok else 1

    rendered = render_all(args.out)
    for name in rendered:
        print(f"wrote {os.path.join(args.out, name)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
